export const products = [
 {id:'AAP-A1',slug:'a1-nearfield',name:'A1 Nearfield Monitor',family:'A-Series',division:'Professional',image:'a1-nearfield.png',statement:'Truth, at working distance.',description:'A compact two-way active monitor for rooms where placement, translation and long sessions all matter.',engineering:'A precision-moulded waveguide and low-distortion midwoofer hold response consistent on and off axis, reducing the room’s ability to mislead the listener.',specs:[['Frequency response','42 Hz–22 kHz ±1.5 dB'],['Peak SPL','118 dB pair'],['Amplification','450 W Class D, bi-amplified'],['Inputs','Analogue XLR + AES3'],['LF driver','6.5 in aluminium cone'],['HF driver','1 in soft dome'],['Dimensions','340 × 220 × 310 mm'],['Weight','12.8 kg']]},
 {id:'AAP-A3',slug:'a3-nearfield',name:'A3 Nearfield Monitor',family:'A-Series',division:'Professional',image:'a3-nearfield.png',statement:'Nearfield precision. Midfield authority.',description:'A three-way active monitor for commercial rooms, scoring stages and post-production suites.',engineering:'A coaxial mid/high assembly preserves image stability while the dedicated low-frequency system supplies headroom without turning the monitor into a room problem.',specs:[['Frequency response','34 Hz–24 kHz ±1.2 dB'],['Peak SPL','123 dB pair'],['Amplification','900 W Class D, tri-amplified'],['Inputs','Analogue XLR + AES3 + network'],['LF driver','8.5 in carbon-paper composite'],['MF/HF','4 in / 1 in coaxial'],['Dimensions','520 × 300 × 390 mm'],['Weight','24.6 kg']]},
 {id:'AAP-M3',slug:'m3-main',name:'M3 Main Monitor',family:'M-Series',division:'Professional',image:'m3-main.png',statement:'Scale without uncertainty.',description:'A large-format main monitoring system for mastering, film, broadcast and high-output control rooms.',engineering:'RoomField commissioning aligns the complete loudspeaker, low-frequency array and room model. Published performance applies only after installation sign-off.',specs:[['Frequency response','22 Hz–24 kHz ±1 dB'],['Peak SPL','132 dB pair'],['Amplification','3.2 kW external DSP amplifiers'],['Inputs','AES3 + network audio'],['LF system','Dual 15 in constrained-layer'],['Mid/high','Horn-loaded coaxial assembly'],['Installation','Flush or freestanding engineered frame'],['Commissioning','Required']]},
 {id:'AAP-SB8',slug:'signal-bridge-8',name:'Signal Bridge 8',family:'Signal Bridge',division:'Professional',image:'signal-bridge-8.png',statement:'Conversion without drama.',description:'Eight channels of reference analogue conversion, stable clocking and low-latency network integration.',engineering:'The power, clock and analogue stages are isolated physically and electrically. Recallable calibration lets facilities verify rather than assume channel matching.',specs:[['Channels','8 analogue in / 8 analogue out'],['Sample rates','44.1–192 kHz'],['Dynamic range','128 dB A-weighted'],['Latency','0.38 ms minimum'],['Digital I/O','AES3, ADAT, network audio'],['Clock','Word clock in / out'],['Format','1U, 19 in rack'],['Power','Universal 100–240 V']]},
 {id:'AAP-C1',slug:'c1-monitor-control',name:'C1 Monitor Controller',family:'Control',division:'Professional',image:'c1-monitor-control.png',statement:'Every route, visible.',description:'Recallable monitoring and routing control for multi-room recording, mastering and broadcast facilities.',engineering:'A fail-safe analogue level path is paired with networked configuration, calibrated speaker trims and permission-aware recall. The operator can always see what the system is doing.',specs:[['Speaker outputs','3 stereo + 2 subwoofer'],['Sources','8 stereo / surround expandable'],['Level path','Relay-switched analogue'],['Recall','User, room and session profiles'],['Talkback','Dual mic with routing matrix'],['Control','Desktop, rack engine, network'],['Metering','Peak, loudness and correlation'],['Redundancy','Bypass monitoring path']]},
 {id:'AAP-H1',slug:'h1-reference',name:'H1 Reference Headphones',family:'Reference',division:'Reference',image:'h1-reference.png',statement:'A room you can carry.',description:'Open-back reference headphones for engineers, musicians and long critical-listening sessions.',engineering:'Matched dynamic drivers, serialised calibration and replaceable wear parts support real working life. Voicing is neutral enough for decisions and humane enough for hours.',specs:[['Type','Open-back circumaural'],['Driver','50 mm low-distortion dynamic'],['Response','8 Hz–42 kHz'],['Impedance','80 Ω'],['Sensitivity','104 dB / 1 V'],['Weight','385 g without cable'],['Cable','Replaceable dual-entry'],['Calibration','Serialised pair record']]},
 {id:'AAP-R1',slug:'r1-reference-monitor',name:'R1 Reference Monitor',family:'Reference',division:'Reference',image:'r1-reference-monitor.png',statement:'Professional judgement, at home.',description:'A compact active reference loudspeaker for critical domestic listening and private work rooms.',engineering:'A domestic enclosure and finish conceal the same controlled-directivity and repairable architecture used by the professional range. RoomField setup is local and privacy-preserving.',specs:[['Frequency response','38 Hz–22 kHz ±1.5 dB'],['Peak SPL','114 dB pair'],['Amplification','300 W bi-amplified'],['Inputs','XLR, AES3, optical, network'],['Room correction','RoomField Local'],['Finish','Dark ash or natural walnut'],['Dimensions','380 × 235 × 320 mm'],['Weight','11.4 kg']]},
 {id:'AAP-D1',slug:'d1-reference-dac',name:'D1 Reference DAC',family:'Reference',division:'Reference',image:'d1-reference-dac.png',statement:'The quiet between numbers.',description:'Reference conversion and headphone amplification with a deliberately simple signal path.',engineering:'Low-noise power, isolated digital inputs and relay attenuation keep the D1 useful as both a desktop reference and the front end of a private listening system.',specs:[['Conversion','PCM to 384 kHz · DSD256'],['Dynamic range','131 dB A-weighted'],['Outputs','Balanced XLR · RCA · 4-pin XLR'],['Inputs','USB-C · AES3 · optical · coaxial'],['Headphone power','6 W / channel at 32 Ω'],['Volume','Relay-switched analogue'],['Display','Dimmable amber OLED'],['Dimensions','280 × 70 × 230 mm']]}
];

export const services = [
 {slug:'professional-audio',title:'Professional Audio',lead:'Monitoring, conversion and control for rooms where a bad decision becomes permanent.',copy:'A-Series, M-Series, Signal Bridge, Control and RoomField form a serviceable professional system backed by installation, commissioning, calibration and training.',steps:['System and room brief','Controlled demonstration','Configuration and integration','Installation and calibration','Training and long-life service']},
 {slug:'reference-products',title:'Reference Products',lead:'Neutral, serviceable listening tools for work and serious private listening.',copy:'Replaceable pads, cables and wear parts; no annual cosmetic refresh cycle; high price justified by engineering and support rather than scarcity theatre.',steps:['Product matching','Specialist demonstration','Room or headphone calibration','Owner documentation','Recertification and service']},
 {slug:'technology',title:'Technology & Licensing',lead:'DSP, spatial and transducer-control tools designed to survive real products.',copy:'Albury Core and RoomField support mobile, automotive, headphone, broadcast and premium-home programmes through embedded software, reference design and validation.',steps:['Use-case and constraint definition','Reference implementation','Integration support','Perceptual and bench validation','Licence and lifecycle support']},
 {slug:'studio-design',title:'Studio Design',lead:'The room as a functioning instrument.',copy:'Feasibility, isolation, geometry, treatment, power, grounding, monitoring, wiring, commissioning and training are coordinated as one technical responsibility.',steps:['Brief and site-risk definition','Measurement and acoustic model','Architecture and engineering coordination','Construction observation','Commissioning and listening tests']},
 {slug:'acoustics-consulting',title:'Acoustics Consulting',lead:'Sound as architecture, product behaviour and human experience.',copy:'Venue, cinema, automotive, hospitality, workplace and noise-sensitive projects receive documented findings early enough for honest design and cost decisions.',steps:['Problem definition','Measurement and investigation','Model and option testing','Design coordination','Performance verification']}
];
