import { mkdir, writeFile } from 'node:fs/promises';
import { projects, divisions } from './project-data.mjs';
const root = new URL('.',import.meta.url);
const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const csv = rows => rows.map(r => r.map(v => `"${String(v ?? '').replaceAll('"','""')}"`).join(',')).join('\n')+'\n';

function shell({title,description,depth=1,current='',body}) { const p='../'.repeat(depth); const nav=[['Work','work/'],['Originals','divisions/originals.html'],['Distribution','divisions/distribution.html'],['Audio','divisions/audio.html'],['Studios','divisions/studios.html'],['About','about/']]; return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#050505"><meta name="description" content="${esc(description)}"><title>${esc(title)} — Phoenix Media</title><link rel="icon" href="data:,"><link rel="stylesheet" href="${p}styles.css"><script src="${p}script.js" defer></script></head><body class="inner-page"><a class="skip-link" href="#main-content">Skip to content</a><header class="site-header"><a class="wordmark" href="${p}index.html">Phoenix Media</a><button class="nav-toggle" type="button" aria-expanded="false" aria-controls="site-nav"><span class="sr-only">Open navigation</span><span></span><span></span></button><nav class="site-nav" id="site-nav">${nav.map(([label,path])=>`<a href="${p}${path}"${current===label?' aria-current="page"':''}>${label}</a>`).join('')}</nav></header><main id="main-content">${body}</main><footer class="site-footer"><a href="${p}https://walker-holdings.vercel.app/index.html">A Walker Holdings company</a><span>Los Angeles · London · New York</span><span>© <span data-year></span> Phoenix Media</span></footer></body></html>`; }

function projectCard(project,p='../') { return `<a class="project-card" href="${p}projects/${project.slug}.html" data-format="${project.format.toLowerCase()}" data-status="${project.status.toLowerCase()}"><div><img src="${p}assets/${project.image}" alt="Production still for ${esc(project.title)}" loading="eager"><span>${project.id}</span></div><p>${esc(project.format)} · ${esc(project.year)}</p><h2>${esc(project.title)}</h2><strong>${esc(project.logline)}</strong></a>`; }

function projectPage(project) { const related=projects.filter(p=>p.slug!==project.slug).sort((a,b)=>a.strand===project.strand?-1:b.strand===project.strand?1:0).slice(0,3); const credits=[['Director',project.director],['Producer',project.producer],['Executive producer','Rachel Linden'],['Cinematography','Luca Moretti'],['Editor','Clare Donovan'],['Sound','Tom Fitzgerald'],['Production manager','Diego Alvarez']]; return shell({title:project.title,description:project.logline,depth:1,current:'Work',body:`<a class="project-back" href="../work/index.html">← Back to all work</a><section class="project-hero"><img src="../assets/${project.image}" alt="Production still for ${esc(project.title)}"><div class="frame-corners" aria-hidden="true"></div><div class="project-title"><h1>${esc(project.title)}</h1><p>${esc(project.logline)}</p><strong>${esc(project.format)} · ${esc(project.duration)} · ${esc(project.year)}</strong></div><div class="project-timecode" aria-hidden="true"><span>${project.id}</span><span>▶ &nbsp; 01:00:23:16</span><span>SR 25</span></div></section><section class="synopsis"><h2>Synopsis</h2><p>${esc(project.synopsis)}</p><aside><span>A Phoenix Media production</span><strong>Directed by ${esc(project.director)}</strong></aside></section><section class="project-story"><div><h2>The work</h2><p>${esc(project.logline)}</p></div><img src="../assets/${project.image}" alt="Scene from ${esc(project.title)}" loading="eager"><img src="../assets/${related[0].image}" alt="Related Phoenix production texture" loading="eager"><div><h2>Production notes</h2><p>${esc(project.notes)}</p></div></section><section class="project-credits"><h2>Credits</h2>${credits.map(([role,name])=>`<dl><dt>${role}</dt><dd>${esc(name)}</dd></dl>`).join('')}</section><section class="availability"><div><h2>Screenings &amp; availability</h2><p>${esc(project.availability)}</p></div><dl><div><dt>Status</dt><dd>${esc(project.status)}</dd></div><div><dt>Lead office</dt><dd>${esc(project.office)}</dd></div><div><dt>Rights</dt><dd>${esc(project.rights)}</dd></div><div><dt>Strand</dt><dd>${esc(project.strand)}</dd></div></dl><a href="../enquiries/index.html?project=${project.slug}">Distribution enquiries →</a></section><section class="press-materials"><h2>Press materials</h2><a href="../enquiries/index.html?project=${project.slug}">Press kit</a><a href="../enquiries/index.html?project=${project.slug}">Production stills</a><a href="../enquiries/index.html?project=${project.slug}">Screening information</a><a href="../enquiries/index.html?project=${project.slug}">Accessibility versions</a></section><section class="related-projects"><div><h2>Related projects</h2><a href="../work/index.html">View all work</a></div><div class="project-grid project-grid--related">${related.map(p=>projectCard(p,'../')).join('')}</div></section>`}); }

const work = shell({title:'Work',description:'Phoenix Media films, series, documentary podcasts and library restorations.',current:'Work',body:`<header class="work-index-hero"><h1>Stories with evidence.<br><span>Work with a pulse.</span></h1><p>Original films, premium factual series, authored audio and restored library work.</p></header><nav class="project-filters" aria-label="Filter projects"><button class="is-active" data-project-filter="all">All work</button><button data-project-filter="feature">Feature documentaries</button><button data-project-filter="series">Series</button><button data-project-filter="podcast">Audio</button><button data-project-filter="library">Restoration</button></nav><section class="project-grid" data-project-grid>${projects.map(p=>projectCard(p)).join('')}</section>`});

const divisionPages = divisions.map(div => [div.slug,shell({title:div.title,description:div.lead,current:div.slug==='originals'?'Originals':div.slug==='distribution'?'Distribution':div.slug==='audio'?'Audio':div.slug==='studios'?'Studios':'',body:`<header class="division-hero"><div><span>PHX / ${div.slug.toUpperCase()}</span><h1>${div.title}</h1><p>${div.lead}</p></div><strong>${div.metric}</strong></header><section class="division-statement"><h2>Built for the whole life of a story.</h2><p>${div.copy}</p></section><section class="division-capabilities"><h2>Capabilities</h2><ol>${div.capabilities.map((cap,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><strong>${cap}</strong></li>`).join('')}</ol></section><section class="division-work"><div><h2>Relevant work</h2><a href="../work/index.html">Complete slate</a></div><div class="project-grid project-grid--related">${projects.filter(p=>div.slug==='audio'?p.format.includes('podcast'):div.slug==='library'?p.format.includes('restoration'):div.slug==='distribution'?p.rights.includes('distribution')||p.status==='Acquired':!p.format.includes('podcast')).slice(0,3).map(p=>projectCard(p,'../')).join('')}</div></section><section class="division-enquiry"><h2>Bring the question, access and constraints.</h2><a href="../enquiries/index.html?division=${div.slug}">Start a conversation →</a></section>`})]);

const about = shell({title:'About',description:'Phoenix Media company, editorial doctrine and leadership.',current:'About',body:`<header class="division-hero"><div><span>PHX / ABOUT</span><h1>Independent work. Professional infrastructure.</h1><p>Founded in 1995, Phoenix operates across Los Angeles, London and New York.</p></div><strong>Chief Executive · Rachel Linden</strong></header><section class="division-statement"><h2>Access is not the same as truth.</h2><p>Phoenix develops and distributes work with evidence, contributor care and a clear record of conflict. Shared ownership never removes rights cost or editorial responsibility.</p></section><section class="doctrine"><ol><li><span>01</span><h2>The subject does not receive final cut.</h2></li><li><span>02</span><h2>Music clearance begins in development.</h2></li><li><span>03</span><h2>Synthetic media never fabricates testimony.</h2></li><li><span>04</span><h2>Evidence must carry the claim made of it.</h2></li></ol></section>`});

const enquiry = shell({title:'Enquiries',description:'Development, distribution, studio and press enquiries for Phoenix Media.',body:`<header class="work-index-hero"><h1>Start with the work.</h1><p>Tell us whether you are bringing a project, requesting rights, booking facilities or seeking press materials.</p></header><section class="phoenix-form"><form action="mailto:hello@phoenixmedia.example" method="post" enctype="text/plain"><label>Name<input required name="name"></label><label>Organisation<input name="organisation"></label><label>Email<input required type="email" name="email"></label><label>Enquiry<select name="type"><option>Development</option><option>Distribution and sales</option><option>Audio</option><option>Library licensing</option><option>Studio services</option><option>Press</option></select></label><label class="full">Project<input name="project" data-project-field></label><label class="full">Context, territory, timing and materials required<textarea required name="message" rows="8"></textarea></label><button type="submit">Prepare email enquiry →</button></form><aside><h2>Offices</h2><p>Los Angeles · Production, Studios, Library</p><p>London · Originals, Audio</p><p>New York · Audio, Sales</p></aside></section>`});

await Promise.all(['work','projects','divisions','about','enquiries'].map(p=>mkdir(new URL(p+'/',root),{recursive:true})));
await writeFile(new URL('work/index.html',root),work); await writeFile(new URL('about/index.html',root),about); await writeFile(new URL('enquiries/index.html',root),enquiry);
await Promise.all(projects.map(p=>writeFile(new URL(`projects/${p.slug}.html`,root),projectPage(p))));
await Promise.all(divisionPages.map(([slug,page])=>writeFile(new URL(`divisions/${slug}.html`,root),page)));
const dataRoot=new URL('../04_PHOENIX_MEDIA/data/',root);
await writeFile(new URL('project_catalogue.csv',dataRoot),csv([['project_id','slug','title','format','strand','status','release_year','lead_office','rights_position','duration','director','producer','logline','image','source'],...projects.map(p=>[p.id,p.slug,p.title,p.format,p.strand,p.status,p.year,p.office,p.rights,p.duration,p.director,p.producer,p.logline,p.image,'output_slate.csv + expanded website canon'])]));
await writeFile(new URL('project_credits.csv',dataRoot),csv([['project_id','role','name','status'],...projects.flatMap(p=>[[p.id,'Director',p.director,'fictional-expanded'],[p.id,'Producer',p.producer,'fictional-expanded'],[p.id,'Executive producer','Rachel Linden','fictional-expanded']])]));
console.log(`Built ${projects.length} Phoenix project pages and ${divisionPages.length} division pages.`);
